name:                slowql
version:             0.1.0.0
github:              "githubuser/slowql"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/slowql#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- bytestring
- lrucache
- memory
- time
- directory
- binary
- data-binary-ieee754
- utf8-string
- split
- unordered-containers
- bitarray
- containers
library:
  source-dirs: src

executables:
  slowql-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slowql

tests:
  slowql-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slowql
